# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  organization_name: 'Galenus IDP'
  x509_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIEeTCCA2GgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCQ0Ex
    CzAJBgNVBAgMAkJDMREwDwYDVQQKDAhQaGFybVNjaTETMBEGA1UECwwKQmlvUGh5
    c2ljczESMBAGA1UEAwwJc2FtbXkuaWRwMTAwLgYJKoZIhvcNAQkBFiF3ZWJtYXN0
    ZXJAZ2FsZW51cy5waGFybXNjaS51YmMuY2EwHhcNMTcwNzE4MjAwOTAzWhcNMjIw
    NzE3MjAwOTAzWjCBiDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAkJDMREwDwYDVQQK
    DAhQaGFybVNjaTETMBEGA1UECwwKQmlvUGh5c2ljczESMBAGA1UEAwwJc2FtbXku
    aWRwMTAwLgYJKoZIhvcNAQkBFiF3ZWJtYXN0ZXJAZ2FsZW51cy5waGFybXNjaS51
    YmMuY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIupGh35ap/bol
    j5agG3MFSvvcKH+oJGqryOlcOagAQ0GsYM8OhXqbdFWxnpa9WGocBeA+4MDBC2QC
    7hNn3t/UWCyY7zjCmtUvx5s5MkD0J9OqRHXU41YvAqpobvnAYNdWtyBTGPGdCJgB
    c6Ehi7EMHco3fqYgTBAyVdzNmBkCeVTkuGxJacsXEiDZ+VwN/oUthYO5QNXBf6Tn
    8LMQ9enFYVcgZEnesMDWBcOnB9J3RtTstIVtC2B8myC1K2IX0IyRepN6SK7tUV8W
    yj9u33LipMWHP7A/vuOGS2LEIz/KpkfMY08RkNzJrGM7QsFLIUfd+bLBqnQm+Qb1
    4ecZNZhHAgMBAAGjgeswgegwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUt7zq
    woMjJtbcnoQDdQs9mNbNRtowgbUGA1UdIwSBrTCBqoAUt7zqwoMjJtbcnoQDdQs9
    mNbNRtqhgY6kgYswgYgxCzAJBgNVBAYTAkNBMQswCQYDVQQIDAJCQzERMA8GA1UE
    CgwIUGhhcm1TY2kxEzARBgNVBAsMCkJpb1BoeXNpY3MxEjAQBgNVBAMMCXNhbW15
    LmlkcDEwMC4GCSqGSIb3DQEJARYhd2VibWFzdGVyQGdhbGVudXMucGhhcm1zY2ku
    dWJjLmNhggEAMA0GCSqGSIb3DQEBCwUAA4IBAQA+aGNEUds6EYEaBtpCw0s1mtt9
    jNVER0rK900Gu6NE8ZLWwJ1ejJUc6BXnJ7Jfl9I9ItYHtgB/dtCx0X4CXJ1e8Otr
    VM9lEzopEa511BIObzifOI7cJ3HBlevjgCjL8iTzNyTNg1DGd/7Zbw0fr2fM1/9r
    JFMN2pODXRbLAAyIOYU2DNQDH8A5jSkFIfN8ZpT5Fyp5d4mJK1ueNI4UoEizFnvC
    QvXjnunvOnud3DmyLXG3C+aaLChxgJUDXhgPttvW/Y7sDmd2J/OGs4zZ4hvaoxk3
    vBc0f0Lm0Uigz+BPGx/VghpdE5dqX+yxopZKz3xXA4Qtt4hzpRoy/MGLQa08
    -----END CERTIFICATE-----

  secret_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAyLqRod+Wqf26JY+WoBtzBUr73Ch/qCRqq8jpXDmoAENBrGDP
    DoV6m3RVsZ6WvVhqHAXgPuDAwQtkAu4TZ97f1FgsmO84wprVL8ebOTJA9CfTqkR1
    1ONWLwKqaG75wGDXVrcgUxjxnQiYAXOhIYuxDB3KN36mIEwQMlXczZgZAnlU5Lhs
    SWnLFxIg2flcDf6FLYWDuUDVwX+k5/CzEPXpxWFXIGRJ3rDA1gXDpwfSd0bU7LSF
    bQtgfJsgtStiF9CMkXqTekiu7VFfFso/bt9y4qTFhz+wP77jhktixCM/yqZHzGNP
    EZDcyaxjO0LBSyFH3fmywap0JvkG9eHnGTWYRwIDAQABAoIBAAOJnjVvHlWinhw5
    Wps5wJ4wQx4PLKjG84ZRhSNV9MsEZGzoS93iplWFCFmYBOoTW9NgmyIgjeUZEUsn
    7PmgqOsyHp8XYDW1ytoLt4WbiB+FcCqJCFaXJxavAlfS1N36FvF1SsGMJ/3vf9ZO
    tmFD9/vRrpWpyr24+XQZpUmOS6qKdtp2CJaK3aUDjad+ZbD3GvSNqfaVnRdMGJRz
    ludEexjnJTLD4gV8NSR7vMSD/QHgDBJqJ+rJYIlO3JFoFPY66/+4eUJnxE3zc/Q8
    NSyfAYmqOgP9DqThqyNgG4SbnkXW7LMztTNNp03ePfFuln3sJ5xDZvPoLXwVGdX5
    09D8l4kCgYEA9xdNOIKhUtQeGcWD1lfW3OjuvjeXxSMgxafPjSuxV6Hrzi3GrnWw
    2z/CjuVJZsEGjzqM+BbubaoQhKQE/q8htbUFfDuuV64AkQHzFDeHcx2b1nGpQ136
    t6UWHWC7S9GNRVyJcA86YMVENgnA4cJhujuq/N64N9wprFAajQT3p4MCgYEAz/dV
    sRmT5gCjM2YDVYjDRQvupmvPs/2i8b9Q8dc4E+/71FOtnOFNVV1TjVvXWcn3JCAK
    OK5DOLXcbJNVS5+tPKzrrOG6Um8F6Pg2YqpWaZE44UtuY5Ydti0tiX8U3NILXpz5
    66PzDYW6AWFD1Fa8HEffnlLZGlKozlRJuaY3LO0CgYB6TpZyunaQQV8E8rfniWNZ
    xhMnJO2DL3gxXndmMZJ/Bi9qx03pXWhFnrH3eZdzvWg5zYmp4+/xaJT0kxvF1Xqi
    LxCgBgqua/rrzEM+Zp4tZSKWa3yVVBeef6EKua78QKXlB4Egbuk+rWauOPW4yjcF
    sDNbKAOX4urd2GjMFQFhcQKBgCbyCaElyhWrjuSEOSGef/sBNgsCa54oZIhjLJRt
    mnnZWk6z8PJNGv9ef9QcG+MbuGWSfneI4tvO6t2GZdXIrFeNhoEUsKDZW8D6Iq0t
    ews//+fpCV4q8Zt5MGrsWorT5v8r5H2lcVHZ9jBl957fM1EUgKMUnsWYLzacgEX9
    A54tAoGAZBeeWkv3JTfdlyerSwcg9y+mrh+2Gt6htmUmT2v0yQBEhuaT6hxvL3nW
    qsvjYxtDUe2XSzFrMkD6LX5LgkJvpuDOnKv0qzU7ZHavzIh/03Kvf+LnrBQyVsyX
    CBwOzEcVK/S4s9E4r/D9ahrz1E2dVWDZXS2VRZiIK4Q9XeHSOFc=
    -----END RSA PRIVATE KEY-----
  
    base: http://localhost:3011

development:
  secret_key_base: b480b70db4bb404885848754b9c52286835479782867924d2bef2cd50c27457220ee0b87efc86481431509de49a838683c6d5de06d82e3f025dd3c4e6a856ec5 

test:
  secret_key_base: baf69f5efbdd935cd285cc1df6571b8f08d6b85d3a78243ecd7e28108c0664036ecbef2dfe974215fa395b945fdcd0be0fd1217a47fa002436aab90c2b1af54f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  base: http://galenus.pharmsci.ubc.ca/sammy
  
