# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  organization_name: 'Galenus IDP'
  x509_certificate: |
    -----BEGIN CERTIFICATE-----
    MIICkzCCAfwCCQDqegaCppMrBDANBgkqhkiG9w0BAQsFADCBjTELMAkGA1UEBhMC
    Q0ExCzAJBgNVBAgMAkJDMRIwEAYDVQQHDAlWYW5jb3V2ZXIxDDAKBgNVBAoMA1VC
    QzERMA8GA1UECwwIUGhhcm1TY2kxFDASBgNVBAMMC0pvbiBCcmFtYmxlMSYwJAYJ
    KoZIhvcNAQkBFhdqb25hdGhhbi5icmFtYmxlQHViYy5jYTAeFw0xNzA2MjIxODA1
    MDNaFw0xODA2MjIxODA1MDNaMIGNMQswCQYDVQQGEwJDQTELMAkGA1UECAwCQkMx
    EjAQBgNVBAcMCVZhbmNvdXZlcjEMMAoGA1UECgwDVUJDMREwDwYDVQQLDAhQaGFy
    bVNjaTEUMBIGA1UEAwwLSm9uIEJyYW1ibGUxJjAkBgkqhkiG9w0BCQEWF2pvbmF0
    aGFuLmJyYW1ibGVAdWJjLmNhMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7
    +chSuvUVY0POLmlMYqsztdRwm1YmCsHqCXl3Csa2zhIA/MgpbzKKoeoqf5geTk5v
    BF11V3wJ0R+ZIDILEcOBllJraB5aj3htk5GmPdfIrLlzxS6oWZTABYfe5Fg6m8vq
    KlYDikvLuTTt4M4ZgPIfHWiJ2elLu2QPSAvCUxbuEwIDAQABMA0GCSqGSIb3DQEB
    CwUAA4GBAD/4xcFzTxyeky5G39nbs+i4oM2/n7e4M9VmNoQ7oXmaojHObsnYgCto
    /jkaT3O2yM/+LQrTZlNAs4AKTNDuszDRsy/VJ05MFj83cA9gJGTerW6+BrZZXm8t
    b1DvxDlFRvwlrLefFtmGnc1lXAYjcTxNopVAi36rdDilD9mXxdYf
    -----END CERTIFICATE-----

  secret_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQC7+chSuvUVY0POLmlMYqsztdRwm1YmCsHqCXl3Csa2zhIA/Mgp
    bzKKoeoqf5geTk5vBF11V3wJ0R+ZIDILEcOBllJraB5aj3htk5GmPdfIrLlzxS6o
    WZTABYfe5Fg6m8vqKlYDikvLuTTt4M4ZgPIfHWiJ2elLu2QPSAvCUxbuEwIDAQAB
    AoGAYEFUsgBoNY6CDxc29lVkI3ONmCgC4jIKACTf3PRYsw0srPLEMGtvbwvgU+jI
    ZWRlx3VtwgONUZ2TV57j4UU0XcsqCnXZ82kj/w0LX70Kassjys81sZa5lo0Btsk3
    VnVuhOXN95de+qn4oT5DZiv9+VH6pN13smqyb05qSN7g46ECQQDoXcH3Yu2AHRIi
    Aq5x2Bo278mlrghqcbMlCQFUHYf4njcQyJzaZ/pPK383CJWUl1z7VetKxuedwyKM
    lNk6s6IDAkEAzxg0i1Q+LOfwT4Zu+LUVxjlrm9FjP1MpBWJgChGFvRmO6I5zaJk8
    Pfkk4+EkVFAJwY8dhk3V39kCJW7gLS1OsQJAB105UXrMJhxFv9gv6SG9KvKMhHiw
    gZca41iWtzC8Z2+0NQ72kaFr+GhbfsYB35SweLKvY05Mdt6BUM1C2S5qOwJALNFZ
    NbnyhrdfO2alh29xGef9UMhcySyPGRo0HJm0LrtkQRHrCfz3m5XalPJ5cUGtCtWV
    FyarHXmSTFWVcFF40QJBAKQ+deZ5vTsClyoTuaiWYkHpyEUigEDm4EcRfUa7e5xt
    UyACOvtCP3W8maLlCQA8hvi/8Mq7Hu2OC2zwX1Tlj6Q=
    -----END RSA PRIVATE KEY-----
  
    base: http://localhost:3011

development:
  secret_key_base: b480b70db4bb404885848754b9c52286835479782867924d2bef2cd50c27457220ee0b87efc86481431509de49a838683c6d5de06d82e3f025dd3c4e6a856ec5 

test:
  secret_key_base: baf69f5efbdd935cd285cc1df6571b8f08d6b85d3a78243ecd7e28108c0664036ecbef2dfe974215fa395b945fdcd0be0fd1217a47fa002436aab90c2b1af54f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  base: http://galenus.pharmsci.ubc.ca/sammy
  
